version: "3"

services:
    geoserver:
        image: kartoza/geoserver:2.18.0
        container_name: geoserver
        ports:
            - "8081:8080"
        environment:
            TZ: "UTC"
        volumes:
            - ./geoserver_data:/opt/geoserver/data_dir

    postgres:
        build:
            context: .
            dockerfile: PgDockerfile
        container_name: postgres
        ports:
            - "5434:5432"
        environment:
            POSTGRES_DB: kkpr_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: danudenny@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        volumes:
            - ./pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
